require("../css/xiangQing.css");
//监听socket传来的信息
require("jquery");
require("bootstrap");
require("bootstrap-loader");
$.ajax({	
	type:"POST",
	url:"/xiangQingAction/selectXinXi",
	dataType:"json",
	data:{},
	success:function(data){
		$("#con_name").append(data.movie.movie_name)
	},
	error:function(){
		alert("错误");
	}
});